# Generated by Django 3.0.7 on 2020-06-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20200614_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], default='M', max_length=2),
        ),
    ]
