# Generated by Django 3.0.7 on 2020-06-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20200615_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
