# Generated by Django 3.0.7 on 2020-06-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
