# Generated by Django 3.0.7 on 2020-06-16 00:12

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20200615_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(null=True, upload_to=produto.models.get_file_path),
        ),
    ]
