# Generated by Django 3.0.7 on 2020-06-16 00:16

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20200615_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='foto',
            new_name='foto1',
        ),
        migrations.AddField(
            model_name='produto',
            name='foto2',
            field=models.FileField(null=True, upload_to=produto.models.get_file_path),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto3',
            field=models.FileField(null=True, upload_to=produto.models.get_file_path),
        ),
    ]
